<?php

/**
 * @file
 * Contains oauth2_key.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function oauth2_key_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oauth2_key module.
    case 'help.page.oauth2_key':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('helps storing oauth2 tokens using key module and retrieving them.') . '</p>';
      return $output;

    default:
  }
}

